import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./_components/Navigation/Header";
import { AuthProvider } from "./context/Authorization";
import {Roboto_Mono} from 'next/font/google'
import LayerLeft from "./_components/Navigation/LayerLeft";


const RobotoMono = Roboto_Mono({
  subsets: ['latin'],
  variable: '--font-caption'
});
 

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  

  return (
    <html lang="en">
      <body
        className={`${RobotoMono.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
        <Header />
        <LayerLeft>
        {children}
        </LayerLeft>
        </AuthProvider>
      </body>
    </html>
  );
}
